/* This file was generated by upb_generator from the input file:
 *
 *     state_container.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#ifndef STATE_CONTAINER_PROTO_UPB_H__UPB_MINITABLE_H_
#define STATE_CONTAINER_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

// Must be last.
#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable ear6__state__Preview_msg_init;
extern const upb_MiniTable ear6__state__StateContainer_msg_init;

extern const upb_MiniTableEnum ear6__state__Preview__Format_enum_init;
extern const upb_MiniTableFile state_container_proto_upb_file_layout;

#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "upb/port/undef.inc"

#endif  /* STATE_CONTAINER_PROTO_UPB_H__UPB_MINITABLE_H_ */
