/* This file was generated by upb_generator from the input file:
 *
 *     state_container.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#include <stddef.h>
#include "upb/generated_code_support.h"
#include "state_container.upb_minitable.h"

// Must be last.
#include "upb/port/def.inc"

extern const UPB_PRIVATE(upb_GeneratedExtensionListEntry)* UPB_PRIVATE(upb_generated_extension_list);
typedef struct {
  upb_MiniTableField fields[5];
  upb_MiniTableSubInternal subs[1];
} ear6__state__Preview_msg_init_Fields;

static const ear6__state__Preview_msg_init_Fields ear6_state_Preview__fields = {{
  {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {2, 16, 65, UPB_SIZE(12, 13), 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {3, 20, 66, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {4, 24, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {5, UPB_SIZE(28, 32), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(subenum) = &ear6__state__Preview__Format_enum_init},
}};

const upb_MiniTable ear6__state__Preview_msg_init = {
  &ear6_state_Preview__fields.fields[0],
  UPB_SIZE(40, 48), 5, kUpb_ExtMode_NonExtendable, 5, UPB_FASTTABLE_MASK(56), 0,
#ifdef UPB_TRACING_ENABLED
  "ear6.state.Preview",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeUnknown},
    {0x000c000000000008, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0010000001080010, &upb_DecodeFast_ClosedEnum_Scalar_Tag1Byte},
    {0x0014000002000018, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0018000003000020, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x002000000400002a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeUnknown},
    {0x0000000000000000, &_upb_FastDecoder_DecodeUnknown},
  })
};

typedef struct {
  upb_MiniTableField fields[6];
  upb_MiniTableSubInternal subs[1];
} ear6__state__StateContainer_msg_init_Fields;

static const ear6__state__StateContainer_msg_init_Fields ear6_state_StateContainer__fields = {{
  {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(48, 64), 65, kUpb_NoSub, 6, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(20, 16), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(28, 32), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {5, UPB_SIZE(36, 48), 67, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {6, UPB_SIZE(16, 72), 69, 3, 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &ear6__state__Preview_msg_init},
}};

const upb_MiniTable ear6__state__StateContainer_msg_init = {
  &ear6_state_StateContainer__fields.fields[0],
  UPB_SIZE(56, 80), 6, kUpb_ExtMode_NonExtendable, 6, UPB_FASTTABLE_MASK(56), 4,
#ifdef UPB_TRACING_ENABLED
  "ear6.state.StateContainer",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeUnknown},
    {0x000c000000000008, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0040000001000011, &upb_DecodeFast_Fixed64_Scalar_Tag1Byte},
    {0x001000000400001a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0020000002000022, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x003000000300002a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0048000005090032, &upb_DecodeFast_Message_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeUnknown},
  })
};

const upb_MiniTableEnum ear6__state__Preview__Format_enum_init = {
    64,
    0,
    {
        0x7,
        0x0,
    },
};

static const upb_MiniTable *messages_layout_state_container_proto_upb_file_layout[2] = {
  &ear6__state__Preview_msg_init,
  &ear6__state__StateContainer_msg_init,
};

static const upb_MiniTableEnum *enums_layout_state_container_proto_upb_file_layout[1] = {
  &ear6__state__Preview__Format_enum_init,
};

const upb_MiniTableFile state_container_proto_upb_file_layout = {
  messages_layout_state_container_proto_upb_file_layout,
  enums_layout_state_container_proto_upb_file_layout,
  NULL,
  2,
  1,
  0,
};

#include "upb/port/undef.inc"
