/* This file was generated by upb_generator from the input file:
 *
 *     state_container.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#ifndef STATE_CONTAINER_PROTO_UPB_H__UPB_H_
#define STATE_CONTAINER_PROTO_UPB_H__UPB_H_

#include "upb/generated_code_support.h"
#include "state_container.upb_minitable.h"

// Must be last.
#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif
typedef struct ear6_state_Preview {
  upb_Message UPB_PRIVATE(base);
} ear6_state_Preview;

typedef struct ear6_state_StateContainer {
  upb_Message UPB_PRIVATE(base);
} ear6_state_StateContainer;


typedef enum {
  ear6_state_Preview_FORMAT_UNSPECIFIED = 0,
  ear6_state_Preview_FORMAT_RGBA8888 = 1,
  ear6_state_Preview_FORMAT_PNG = 2
} ear6_state_Preview_Format;



/* ear6.state.Preview */
UPB_INLINE ear6_state_Preview* ear6_state_Preview_new(upb_Arena* arena) {
  return (ear6_state_Preview*)_upb_Message_New(&ear6__state__Preview_msg_init, arena);
}
UPB_INLINE ear6_state_Preview* ear6_state_Preview_parse(const char* buf, size_t size,
                                        upb_Arena* arena) {
  ear6_state_Preview* ret = ear6_state_Preview_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &ear6__state__Preview_msg_init, NULL, 0,
                 arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE ear6_state_Preview* ear6_state_Preview_parse_ex(
    const char* buf, size_t size, const upb_ExtensionRegistry* extreg,
    int options, upb_Arena* arena) {
  ear6_state_Preview* ret = ear6_state_Preview_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &ear6__state__Preview_msg_init, extreg,
                 options, arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE char* ear6_state_Preview_serialize(const ear6_state_Preview* msg,
                                      upb_Arena* arena, size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &ear6__state__Preview_msg_init, 0, arena, &ptr, len);
  return ptr;
}
UPB_INLINE char* ear6_state_Preview_serialize_ex(const ear6_state_Preview* msg,
                                         int options, upb_Arena* arena,
                                         size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &ear6__state__Preview_msg_init, options, arena, &ptr, len);
  return ptr;
}
UPB_INLINE void ear6_state_Preview_clear_version(ear6_state_Preview* msg) {
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint32_t ear6_state_Preview_version(const ear6_state_Preview* msg) {
  uint32_t default_val = (uint32_t)0u;
  uint32_t ret;
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_Preview_has_version(const ear6_state_Preview* msg) {
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_Preview_clear_format(ear6_state_Preview* msg) {
  const upb_MiniTableField field = {2, 16, 65, UPB_SIZE(12, 13), 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE int32_t ear6_state_Preview_format(const ear6_state_Preview* msg) {
  int32_t default_val = 0;
  int32_t ret;
  const upb_MiniTableField field = {2, 16, 65, UPB_SIZE(12, 13), 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_Preview_has_format(const ear6_state_Preview* msg) {
  const upb_MiniTableField field = {2, 16, 65, UPB_SIZE(12, 13), 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_Preview_clear_width(ear6_state_Preview* msg) {
  const upb_MiniTableField field = {3, 20, 66, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint32_t ear6_state_Preview_width(const ear6_state_Preview* msg) {
  uint32_t default_val = (uint32_t)0u;
  uint32_t ret;
  const upb_MiniTableField field = {3, 20, 66, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_Preview_has_width(const ear6_state_Preview* msg) {
  const upb_MiniTableField field = {3, 20, 66, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_Preview_clear_height(ear6_state_Preview* msg) {
  const upb_MiniTableField field = {4, 24, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint32_t ear6_state_Preview_height(const ear6_state_Preview* msg) {
  uint32_t default_val = (uint32_t)0u;
  uint32_t ret;
  const upb_MiniTableField field = {4, 24, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_Preview_has_height(const ear6_state_Preview* msg) {
  const upb_MiniTableField field = {4, 24, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_Preview_clear_image_data(ear6_state_Preview* msg) {
  const upb_MiniTableField field = {5, UPB_SIZE(28, 32), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE upb_StringView ear6_state_Preview_image_data(const ear6_state_Preview* msg) {
  upb_StringView default_val = upb_StringView_FromString("");
  upb_StringView ret;
  const upb_MiniTableField field = {5, UPB_SIZE(28, 32), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_Preview_has_image_data(const ear6_state_Preview* msg) {
  const upb_MiniTableField field = {5, UPB_SIZE(28, 32), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}

UPB_INLINE void ear6_state_Preview_set_version(ear6_state_Preview* msg, uint32_t value) {
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_Preview_set_format(ear6_state_Preview* msg, int32_t value) {
  const upb_MiniTableField field = {2, 16, 65, UPB_SIZE(12, 13), 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_Preview_set_width(ear6_state_Preview* msg, uint32_t value) {
  const upb_MiniTableField field = {3, 20, 66, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_Preview_set_height(ear6_state_Preview* msg, uint32_t value) {
  const upb_MiniTableField field = {4, 24, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_Preview_set_image_data(ear6_state_Preview* msg, upb_StringView value) {
  const upb_MiniTableField field = {5, UPB_SIZE(28, 32), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}

/* ear6.state.StateContainer */
UPB_INLINE ear6_state_StateContainer* ear6_state_StateContainer_new(upb_Arena* arena) {
  return (ear6_state_StateContainer*)_upb_Message_New(&ear6__state__StateContainer_msg_init, arena);
}
UPB_INLINE ear6_state_StateContainer* ear6_state_StateContainer_parse(const char* buf, size_t size,
                                        upb_Arena* arena) {
  ear6_state_StateContainer* ret = ear6_state_StateContainer_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &ear6__state__StateContainer_msg_init, NULL, 0,
                 arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE ear6_state_StateContainer* ear6_state_StateContainer_parse_ex(
    const char* buf, size_t size, const upb_ExtensionRegistry* extreg,
    int options, upb_Arena* arena) {
  ear6_state_StateContainer* ret = ear6_state_StateContainer_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &ear6__state__StateContainer_msg_init, extreg,
                 options, arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE char* ear6_state_StateContainer_serialize(const ear6_state_StateContainer* msg,
                                      upb_Arena* arena, size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &ear6__state__StateContainer_msg_init, 0, arena, &ptr, len);
  return ptr;
}
UPB_INLINE char* ear6_state_StateContainer_serialize_ex(const ear6_state_StateContainer* msg,
                                         int options, upb_Arena* arena,
                                         size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &ear6__state__StateContainer_msg_init, options, arena, &ptr, len);
  return ptr;
}
UPB_INLINE void ear6_state_StateContainer_clear_system_type(ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint32_t ear6_state_StateContainer_system_type(const ear6_state_StateContainer* msg) {
  uint32_t default_val = (uint32_t)0u;
  uint32_t ret;
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_StateContainer_has_system_type(const ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_StateContainer_clear_content_identity(ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {2, UPB_SIZE(48, 64), 65, kUpb_NoSub, 6, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint64_t ear6_state_StateContainer_content_identity(const ear6_state_StateContainer* msg) {
  uint64_t default_val = (uint64_t)0ull;
  uint64_t ret;
  const upb_MiniTableField field = {2, UPB_SIZE(48, 64), 65, kUpb_NoSub, 6, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_StateContainer_has_content_identity(const ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {2, UPB_SIZE(48, 64), 65, kUpb_NoSub, 6, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_StateContainer_clear_content_name(ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {3, UPB_SIZE(20, 16), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE upb_StringView ear6_state_StateContainer_content_name(const ear6_state_StateContainer* msg) {
  upb_StringView default_val = upb_StringView_FromString("");
  upb_StringView ret;
  const upb_MiniTableField field = {3, UPB_SIZE(20, 16), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_StateContainer_has_content_name(const ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {3, UPB_SIZE(20, 16), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_StateContainer_clear_content(ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {4, UPB_SIZE(28, 32), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE upb_StringView ear6_state_StateContainer_content(const ear6_state_StateContainer* msg) {
  upb_StringView default_val = upb_StringView_FromString("");
  upb_StringView ret;
  const upb_MiniTableField field = {4, UPB_SIZE(28, 32), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_StateContainer_has_content(const ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {4, UPB_SIZE(28, 32), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_StateContainer_clear_system_state(ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {5, UPB_SIZE(36, 48), 67, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE upb_StringView ear6_state_StateContainer_system_state(const ear6_state_StateContainer* msg) {
  upb_StringView default_val = upb_StringView_FromString("");
  upb_StringView ret;
  const upb_MiniTableField field = {5, UPB_SIZE(36, 48), 67, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_StateContainer_has_system_state(const ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {5, UPB_SIZE(36, 48), 67, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void ear6_state_StateContainer_clear_preview(ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {6, UPB_SIZE(16, 72), 69, 3, 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE const ear6_state_Preview* ear6_state_StateContainer_preview(const ear6_state_StateContainer* msg) {
  const ear6_state_Preview* default_val = NULL;
  const ear6_state_Preview* ret;
  const upb_MiniTableField field = {6, UPB_SIZE(16, 72), 69, 3, 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&ear6__state__Preview_msg_init);
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool ear6_state_StateContainer_has_preview(const ear6_state_StateContainer* msg) {
  const upb_MiniTableField field = {6, UPB_SIZE(16, 72), 69, 3, 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}

UPB_INLINE void ear6_state_StateContainer_set_system_type(ear6_state_StateContainer* msg, uint32_t value) {
  const upb_MiniTableField field = {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_StateContainer_set_content_identity(ear6_state_StateContainer* msg, uint64_t value) {
  const upb_MiniTableField field = {2, UPB_SIZE(48, 64), 65, kUpb_NoSub, 6, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_StateContainer_set_content_name(ear6_state_StateContainer* msg, upb_StringView value) {
  const upb_MiniTableField field = {3, UPB_SIZE(20, 16), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_StateContainer_set_content(ear6_state_StateContainer* msg, upb_StringView value) {
  const upb_MiniTableField field = {4, UPB_SIZE(28, 32), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_StateContainer_set_system_state(ear6_state_StateContainer* msg, upb_StringView value) {
  const upb_MiniTableField field = {5, UPB_SIZE(36, 48), 67, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void ear6_state_StateContainer_set_preview(ear6_state_StateContainer* msg, ear6_state_Preview* value) {
  const upb_MiniTableField field = {6, UPB_SIZE(16, 72), 69, 3, 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&ear6__state__Preview_msg_init);
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE struct ear6_state_Preview* ear6_state_StateContainer_mutable_preview(
    ear6_state_StateContainer* msg, upb_Arena* arena) {
  struct ear6_state_Preview* sub = (struct ear6_state_Preview*)ear6_state_StateContainer_preview(msg);
  if (sub == NULL) {
    sub = (struct ear6_state_Preview*)_upb_Message_New(&ear6__state__Preview_msg_init, arena);
    if (sub) ear6_state_StateContainer_set_preview(msg, sub);
  }
  return sub;
}

#ifdef __cplusplus
              } /* extern "C" */
#endif

#include "upb/port/undef.inc"

#endif /* STATE_CONTAINER_PROTO_UPB_H__UPB_H_ */
